### ISSUE TITLE
Countdown Timer crashes OBS

### ISSUE THREAD

**Issue by DachsbauTV** [midnight-studios/obs-lua#2]
First off: Thanks for the crazy amount of helpful and amazing scripts!

I've encountered a quite severe bug with the Advanced Stopwatch script:
When set to "Start Timer on source visible" and the countdown running down to a specific date and time, at any change to the settings OBS would completely crash.

So far it happened when changing any of the time settings and also when changing the "Next Scene" setting.

OBS 27.1.3.
Win 10 64
Script version 3.2.

**Comment by midnight-studios** [comment]
Hi, thanks for the report. Please attach the crash report.

**Comment by midnight-studios** [comment]
DOes it creat a crash on OBS Exit, or crash OBS if the chnages are made.

I have not been able to recreate your crash instance.

I suggest, create a new 'Scene Collection' and add a minimum of scene items and the script and note a step by step on how to recreate the bug behaviour.
