### ISSUE TITLE
Feature Request: Advanced Stopwatch: More control over format

### ISSUE THREAD

**Issue by DachsbauTV** [midnight-studios/obs-lua#3]
Hi

It would be great to have more individual control over the format of the timer.

e.g. I would like it to keep the minutes even when under 1min

So maybe it could be separated into several dropdowns:
Days yes/no
hours yes/no
minutes yes/no
seconds yes/no
split seconds yes/no
remove leading zeros yes/no

or just a custom field in which a format can be entered: eg.g mm:ss
plus the "remove leading zeros" option

**Comment by midnight-studios** [comment]
Can you provide a sample of what the timer would look like if it supports your feature request? Please provide a sample for above and below a minute remaining on the timer.

**Comment by DachsbauTV** [comment]
Sure :)

some examples: 
- mm:ss = 02:30
- mm "minutes" ss "seconds" = 02 Minutes 30 Seconds
- ss = 150
- ss"s" = 150s
- dd:hh:mm:ss,sss = 01:01:02:30,25
- m:ss = 2:30

Kind of like this: https://www.ibm.com/docs/en/tap/3.6.0?topic=time-custom-date-formats

**Comment by midnight-studios** [comment]
[Updated](https://obsproject.com/forum/resources/comprehensive-stopwatch-countdown-timer.1364/), thank you.

**Comment by DachsbauTV** [comment]
Amazing work! I will try it this week, but it looks great :)

**Comment by midnight-studios** [comment]
Thank you! Happy to make some adjustments if needed, but I think it will suit your needs...

If it's not to much trouble, please consider rating the Script [here](https://obsproject.com/forum/resources/comprehensive-stopwatch-countdown-timer.1364/):

Its very helpful.
