### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by OpaWattebausch** [midnight-studios/obs-lua#7]
Hi

I use the StopWatch.lua for obs and tried to get the sound for timer expired audio on countdown, but it always crashes my obs as soon as I choose the sound source.

So is there a specific sound format that I have to use? Tried wav, mp3 and  ogg.

obs 29.0.2
StopWatch.lua 4.9

**Comment by midnight-studios** [comment]
Hopefully this has been resolved in the updated versions. If not, please provide your OS version.
