### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by SnekCode** [midnight-studios/obs-lua#9]
Add a way to restart the Countup and keep track of that reset.

I thinking: 
1. A hotkey to reset the timer
2. A text element to increment a count

This would allow users to show time between events.  Like a death counter.

**Comment by midnight-studios** [comment]
Currently, there is a hotkey available to RESET the timer. You can find it, by searching for the hotkey using the SCRIPT NAME. 

Hotkeys available:

1. Start
2. Start/Pause (Pause only if Start Pause is separated via Opt-In in Script Settings)
3. Reset
4. Split/Lap

Some other hotkeys may also be available to manipulate the timer.

You can find a [video on this here](https://www.youtube.com/watch?v=RJEGkfIWcV0&t=452s)

**Comment by midnight-studios** [comment]
> Add a way to restart the Countup and keep track of that reset.
> 
> I thinking:
> > 2. A text element to increment a count
> 
> This would allow users to show time between events. Like a death counter.

Would it truly make sense to add this feature? You could easily achieve this by [using this script](https://obsproject.com/forum/resources/score-board.1448/)

By [using the Score Board](https://obsproject.com/forum/resources/score-board.1448/) in conjunction with Hotkeys, you could assign the same Hotkey to increment the counter as for pausing the counter.
